### ISSUE TITLE
Cannot Seem to get the bot to start.

### ISSUE THREAD

**Issue by markddavidoff** [sofetch/standupbot-open-source#77]
I get a "Well done! Everything is ok, the standup will start soon." response for every /standup command i type.

The web-side shows the users and settings fine but a blank page otherwise.
![capture](https://cloud.githubusercontent.com/assets/1360543/16431093/c6000e6e-3d33-11e6-9560-eee0e33f8fe7.PNG)

**Comment by santiagodoldan** [comment]
Is that the report page? Were you able to complete an entire standup session?

**Comment by markddavidoff** [comment]
No i wasnt able to proceed at all, all /standup commands returned the
everything ok message

**Comment by santiagodoldan** [comment]
Try to double check the log, it's weird that you get the correct message but then you don't get the next message to start the standup session.

**Comment by santiagodoldan** [comment]
Sorry, forgot to add the heroku command

`heroku logs --tail`

**Comment by markddavidoff** [comment]
2 attempts at /standup -start:
2016-06-28T22:58:07.212406+00:00 heroku[router]: at=info method=GET path="/api/s
tandups/start?format=text&token=CZddoE6yON80sDdC4tNt72QO&team_id=T028H5S1U&team_
domain=REDACTED&channel_id=G1M4H1XEU&channel_name=privategroup&user_id=U1GQZ284C
&user_name=REDACTED&command=%2Fstandup&text=-start&response_url=https%3A%2F%
2Fhooks.slack.com%2Fcommands%2FT028H5S1U%2F55202648341%2FEyrjYBcq7mwg9ZhzGL5OA2X
F" host=REDACTED.herokuapp.com request_id=19891e5f-06b4-46f6-88a3-616876ea8a
8b fwd="54.89.92.4" dyno=web.1 connect=1ms service=1468ms status=200 bytes=508

2016-06-28T22:58:17.661132+00:00 heroku[router]: at=info method=GET path="/api/s
tandups/start?format=text&token=CZddoE6yON80sDdC4tNt72QO&team_id=T028H5S1U&team_
domain=REDACTED&channel_id=G1M4H1XEU&channel_name=privategroup&user_id=U1GQZ284C
&user_name=REDACTED&command=%2Fstandup&text=-start&response_url=https%3A%2F%
2Fhooks.slack.com%2Fcommands%2FT028H5S1U%2F55208669473%2FPlGhmI0xusqMdSRGMpOVfGN
U" host=REDACTED.herokuapp.com request_id=f2ef207f-96d2-42bf-bdc2-e82877a230
44 fwd="52.91.184.2" dyno=web.1 connect=1ms service=856ms status=200 bytes=508

**Comment by santiagodoldan** [comment]
hrm, let's try to start a standup from the rails console

`heroku run rails c`

Then you can do the same as the standups_controller

https://github.com/sofetch/standupbot-open-source/blob/master/app/controllers/api/standups_controller.rb#L12

If that doesn't work and you don't see any errors there, you will need to start debugging that code, maybe just using puts statements

**Comment by markddavidoff** [comment]
If I'm reading this correctly, this line exits if the channel is active. Is that the intended path?
https://github.com/sofetch/standupbot-open-source/blob/master/lib/standupbot/client.rb#L28

**Comment by santiagodoldan** [comment]
Yeah, that's to avoid multiple RTM sessions at the same time for the same channel, if we remove that line and one or different users enter the /standup slash command, then you will end seeing duplicated bot messages. makes sense?

**Comment by santiagodoldan** [comment]
Gonna close this issue

**Comment by jlubeck** [comment]
I'm running into this same scenario, but I'm not running on heroku. 

I have the server running, and when I type /standup inside the slack channel, I get "Well done! Everything is ok, the standup will start soon." from the slackbot (which is not the bot I created)

But the standup never actually starts and on the server console I see this error which I don't know if it has something to do with it:

```
Started GET "/api/standups/start?format=text&token=Bxgsi920cgMbU0RR72wDzBab&team_id=T24H90KN0&team_domain=fyrastudio&channel_id=G2J5ZSJCC&channel_name=privategroup&user_id=U24HJQ6DB&user_name=jan&command=%2Fstandup&text=&response_url=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT24H90KN0%2F86211505862%2FHlQKfqcLrz7xTDQpdtUtkxbL" for 52.91.184.228 at 2016-09-30 19:10:14 -0300
Cannot render console from 52.91.184.228! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Api::StandupsController#start as TEXT
  Parameters: {"token"=>"Bxgsi920cgMbU0RR72wDzBab", "team_id"=>"T24H90KN0", "team_domain"=>"fyrastudio", "channel_id"=>"G2J5ZSJCC", "channel_name"=>"privategroup", "user_id"=>"U24HJQ6DB", "user_name"=>"jan", "command"=>"/standup", "text"=>"", "response_url"=>"https://hooks.slack.com/commands/T24H90KN0/86211505862/HlQKfqcLrz7xTDQpdtUtkxbL"}
  Setting Load (0.5ms)  SELECT  "settings".* FROM "settings"  ORDER BY "settings"."id" ASC LIMIT 1
  CACHE (0.0ms)  SELECT  "settings".* FROM "settings"  ORDER BY "settings"."id" ASC LIMIT 1
  CACHE (0.0ms)  SELECT  "settings".* FROM "settings"  ORDER BY "settings"."id" ASC LIMIT 1
  Channel Load (0.7ms)  SELECT  "channels".* FROM "channels" WHERE "channels"."name" = $1 AND "channels"."slack_id" = $2  ORDER BY "channels"."id" ASC LIMIT 1  [["name", "test"], ["slack_id", "G2J5ZSJCC"]]
   (0.2ms)  BEGIN
  User Load (0.7ms)  SELECT "users".* FROM "users" INNER JOIN "channel_users" ON "users"."id" = "channel_users"."user_id" WHERE "channel_users"."channel_id" = $1  [["channel_id", 2]]
  SQL (0.3ms)  DELETE FROM "channel_users" WHERE "channel_users"."channel_id" = $1 AND "channel_users"."user_id" IN (2, 5)  [["channel_id", 2]]
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."slack_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["slack_id", "U24HJQ6DB"]]
  User Exists (0.5ms)  SELECT  1 AS one FROM "users" WHERE ("users"."slack_id" = 'U24HJQ6DB' AND "users"."id" != 2) LIMIT 1
  SQL (0.3ms)  INSERT INTO "channel_users" ("channel_id", "user_id") VALUES ($1, $2) RETURNING "id"  [["channel_id", 2], ["user_id", 2]]
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."slack_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["slack_id", "U2B8NKTC7"]]
  User Exists (0.5ms)  SELECT  1 AS one FROM "users" WHERE ("users"."slack_id" = 'U2B8NKTC7' AND "users"."id" != 5) LIMIT 1
  SQL (0.3ms)  INSERT INTO "channel_users" ("channel_id", "user_id") VALUES ($1, $2) RETURNING "id"  [["channel_id", 2], ["user_id", 5]]
   (2.2ms)  COMMIT
   (0.2ms)  BEGIN
  SQL (0.3ms)  UPDATE "channels" SET "state" = $1 WHERE "channels"."id" = $2  [["state", "active"], ["id", 2]]
   (1.8ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.3ms)  UPDATE "channels" SET "state" = $1 WHERE "channels"."id" = $2  [["state", "idle"], ["id", 2]]
E, [2016-09-30T19:10:15.736478 #10446] ERROR -- : Actor crashed!
TypeError: no implicit conversion from nil to integer
	/home/ubuntu/.rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1266:in `__recvfrom_nonblock'
	/home/ubuntu/.rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1266:in `recvfrom_nonblock'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-io-0.17.2/lib/celluloid/io/udp_socket.rb:22:in `recvfrom'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-io-0.17.2/lib/celluloid/io/dns_resolver.rb:45:in `resolve'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-io-0.17.2/lib/celluloid/io/tcp_socket.rb:63:in `initialize'
	/home/ubuntu/.gem/ruby/2.3.1/gems/slack-ruby-client-0.5.2/lib/slack/real_time/concurrency/celluloid.rb:71:in `new'
	/home/ubuntu/.gem/ruby/2.3.1/gems/slack-ruby-client-0.5.2/lib/slack/real_time/concurrency/celluloid.rb:71:in `build_socket'
	/home/ubuntu/.gem/ruby/2.3.1/gems/slack-ruby-client-0.5.2/lib/slack/real_time/concurrency/celluloid.rb:85:in `connect'
	/home/ubuntu/.gem/ruby/2.3.1/gems/slack-ruby-client-0.5.2/lib/slack/real_time/socket.rb:26:in `connect!'
	/home/ubuntu/.gem/ruby/2.3.1/gems/slack-ruby-client-0.5.2/lib/slack/real_time/concurrency/celluloid.rb:29:in `connect!'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `public_send'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `dispatch'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/call/sync.rb:16:in `dispatch'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/cell.rb:50:in `block in dispatch'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/cell.rb:76:in `block in task'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/actor.rb:339:in `block in task'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/task.rb:44:in `block in initialize'
	/home/ubuntu/.gem/ruby/2.3.1/gems/celluloid-0.17.2/lib/celluloid/task/fibered.rb:14:in `block in create'
   (2.0ms)  COMMIT
  Rendered api/standups/start.text.erb (0.1ms)
Completed 200 OK in 1600ms (Views: 8.7ms | ActiveRecord: 12.1ms)
```
