### ISSUE TITLE
Settings Page Login Problem

### ISSUE THREAD

**Issue by rostendorf** [sofetch/standupbot-open-source#85]
After following the readme and running into zero install or config issues, attempting to navigate and log into the /settings page gets me nowhere, regardless of which credentials I use.

**Comment by santiagodoldan** [comment]
You have to use the configured env variables.

```
**Configure your credentials to access the webpage**
heroku config:set STANDUPBOT_USERNAME=your-username
heroku config:set STANDUPBOT_SECRET=your-secret
```

**Comment by rostendorf** [comment]
Thanks @santiagodoldan -- I completely misread that on the first go around, thinking that was supposed to be my Slack token.
